import type { Tema } from "@/lib/types";

export const temas: Tema[] = [
  {
    slug: "redes",
    nombre: "Internet",
    preguntaGancho: "¿Cómo llega un video de YouTube a tu pantalla en menos de un segundo?",
    iconoLucide: "Network",
    totalCapitulos: 6,
    tiempoEstimadoMin: 60,
    requisitos: "Ninguno",
    prerrequisitos:
      "Cero experiencia técnica requerida. Solo ganas de entender cómo viajan los datos por internet, paso a paso.",
  },
  {
    slug: "linux",
    nombre: "Linux Admin",
    preguntaGancho: "La base de todos los servidores del mundo. También de Google, Netflix y Amazon.",
    iconoLucide: "Terminal",
    totalCapitulos: 6,
    tiempoEstimadoMin: 70,
    requisitos: "Ninguno",
    prerrequisitos:
      "Cero experiencia con la terminal requerida. Va bien después de Internet, pero no obligatorio.",
  },
  {
    slug: "git",
    nombre: "Git",
    preguntaGancho: "¿Cómo trabajan 50 personas sobre el mismo código sin estropearlo?",
    iconoLucide: "GitBranch",
    totalCapitulos: 5,
    tiempoEstimadoMin: 55,
    requisitos: "Familiaridad con la terminal ayuda",
    prerrequisitos: "Recomendado haber visto Linux Admin primero, pero no obligatorio.",
  },
  {
    slug: "seguridad",
    nombre: "Seguridad",
    preguntaGancho: "¿Qué tiene que pasar para que alguien robe una contraseña?",
    iconoLucide: "ShieldCheck",
    totalCapitulos: 6,
    tiempoEstimadoMin: 65,
    requisitos: "Conceptos básicos de Redes",
    prerrequisitos:
      "Se construye sobre Internet (DNS, HTTPS, TCP). Recomendado verlo después.",
  },
  {
    slug: "bases-de-datos",
    nombre: "Bases de Datos",
    preguntaGancho: "¿Dónde vive la información cuando cierras la app?",
    iconoLucide: "Database",
    totalCapitulos: 5,
    tiempoEstimadoMin: 40,
    requisitos: "Ninguno",
    prerrequisitos: "Independiente. Se puede ver en cualquier momento.",
  },
  {
    slug: "docker",
    nombre: "Docker",
    preguntaGancho: "¿Cómo empacar una app entera para abrirla en cualquier dispositivo?",
    iconoLucide: "Container",
    totalCapitulos: 5,
    tiempoEstimadoMin: 40,
    requisitos: "Linux Admin recomendado",
    prerrequisitos: "Conviene venir con Linux fresco en la cabeza.",
  },
  {
    slug: "cloud",
    nombre: "Cloud",
    preguntaGancho: "¿De quién es la computadora que ejecuta todos los programas que usas a diario?",
    iconoLucide: "Cloud",
    totalCapitulos: 6,
    tiempoEstimadoMin: 50,
    requisitos: "Redes y Linux",
    prerrequisitos: "Asume que ya viste Redes y Linux Admin.",
  },
  {
    slug: "terraform",
    nombre: "Terraform",
    preguntaGancho: "¿Y si la infraestructura se escribiera como un archivo de texto?",
    iconoLucide: "FileCode2",
    totalCapitulos: 4,
    tiempoEstimadoMin: 30,
    requisitos: "Cloud",
    prerrequisitos: "Requiere entender conceptos de Cloud primero.",
  },
  {
    slug: "kubernetes",
    nombre: "Kubernetes",
    preguntaGancho: "¿Cómo se orquestan cientos de contenedores al mismo tiempo?",
    iconoLucide: "Boxes",
    totalCapitulos: 5,
    tiempoEstimadoMin: 45,
    requisitos: "Docker y Cloud",
    prerrequisitos: "Necesitás Docker entendido y al menos haber rozado Cloud.",
  },
  // === Inteligencia Artificial (próximamente) ===
  {
    slug: "llm",
    nombre: "LLMs",
    preguntaGancho: "¿Cómo funciona realmente un modelo de lenguaje por dentro?",
    iconoLucide: "Brain",
    totalCapitulos: 5,
    tiempoEstimadoMin: 50,
    requisitos: "Ninguno",
    prerrequisitos:
      "Ideal venir con Prompt Engineering primero, pero no obligatorio. Cero supuestos técnicos.",
  },
  {
    slug: "prompt-engineering",
    nombre: "Prompt Engineering",
    preguntaGancho:
      "¿Por qué la misma pregunta a una IA da resultados mediocres o brillantes según cómo la escribas?",
    iconoLucide: "Sparkles",
    totalCapitulos: 4,
    tiempoEstimadoMin: 30,
    requisitos: "Ninguno",
    prerrequisitos:
      "Ideal antes de Claude Cowork. No requiere experiencia técnica.",
  },
  {
    slug: "rag",
    nombre: "RAG",
    preguntaGancho: "¿Cómo darle a la IA acceso a tus propios documentos?",
    iconoLucide: "BookOpen",
    totalCapitulos: 5,
    tiempoEstimadoMin: 55,
    requisitos: "Ninguno",
    prerrequisitos:
      "Ideal venir con LLMs y Prompt Engineering primero. Sin requisitos técnicos profundos.",
  },
  {
    slug: "mcp",
    nombre: "MCP",
    preguntaGancho: "El protocolo que conecta modelos de IA con herramientas reales.",
    iconoLucide: "PlugZap",
    totalCapitulos: 5,
    tiempoEstimadoMin: 50,
    requisitos: "Ninguno",
    prerrequisitos:
      "Ideal venir con LLMs y Claude Cowork vistos. No requiere experiencia de programación profunda.",
  },
  {
    slug: "claude-cowork",
    nombre: "Claude Cowork",
    preguntaGancho: "Del Chat al Cowork: domina la IA en tu día a día",
    iconoLucide: "Bot",
    totalCapitulos: 5,
    tiempoEstimadoMin: 60,
    requisitos: "Ninguno",
    prerrequisitos: "Primer contacto con IA recomendado pero no obligatorio.",
  },
  {
    slug: "zapier",
    nombre: "Zapier",
    preguntaGancho: "¿Cómo conectar todas tus apps favoritas para que trabajen solas?",
    iconoLucide: "Zap",
    totalCapitulos: 4,
    tiempoEstimadoMin: 30,
    requisitos: "Ninguno",
    prerrequisitos: "Independiente. No se requiere experiencia técnica.",
  },
  {
    slug: "make",
    nombre: "Make",
    preguntaGancho: "Automatización visual sin código para procesos complejos.",
    iconoLucide: "Boxes",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "n8n",
    nombre: "N8N",
    preguntaGancho: "¿Cómo automatizar flujos de trabajo complejos sin escribir código?",
    iconoLucide: "Workflow",
    totalCapitulos: 4,
    tiempoEstimadoMin: 35,
    requisitos: "Ninguno",
    prerrequisitos: "Independiente. Se puede ver en cualquier momento.",
  },
  {
    slug: "microsoft-copilot",
    nombre: "Microsoft Copilot",
    preguntaGancho: "Cómo aprovechar la IA integrada en el ecosistema Microsoft 365.",
    iconoLucide: "Bot",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "gemini",
    nombre: "Gemini",
    preguntaGancho: "El modelo multimodal de Google y su integración con Workspace.",
    iconoLucide: "Gem",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "agentforce",
    nombre: "Agentforce",
    preguntaGancho: "Cómo Salesforce está reinventando la atención al cliente con agentes IA.",
    iconoLucide: "Users",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  // === Data Analysis (próximamente) ===
  {
    slug: "sql",
    nombre: "SQL",
    preguntaGancho: "El lenguaje universal para hacerle preguntas a los datos.",
    iconoLucide: "Database",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "excel",
    nombre: "Excel",
    preguntaGancho: "La herramienta de análisis más usada del mundo, llevada al siguiente nivel.",
    iconoLucide: "Sheet",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "python-pandas",
    nombre: "Python (Pandas)",
    preguntaGancho: "Análisis de datos a escala con la librería estándar de la industria.",
    iconoLucide: "FileCode2",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "power-bi",
    nombre: "Power BI",
    preguntaGancho: "Dashboards interactivos y modelos de datos para tomar decisiones.",
    iconoLucide: "BarChart3",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "tableau",
    nombre: "Tableau",
    preguntaGancho: "Visualización avanzada para contar historias con datos.",
    iconoLucide: "PieChart",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "estadistica",
    nombre: "Estadística",
    preguntaGancho: "Los fundamentos para no engañarte (ni dejar que te engañen) con los datos.",
    iconoLucide: "Sigma",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
  {
    slug: "visualizacion-datos",
    nombre: "Visualización de datos",
    preguntaGancho: "Cómo elegir el gráfico correcto para cada pregunta.",
    iconoLucide: "LineChart",
    totalCapitulos: 0,
    tiempoEstimadoMin: 0,
    requisitos: "Próximamente",
    prerrequisitos: "Contenido en preparación.",
  },
];


export function temaBySlug(slug: string): Tema | undefined {
  return temas.find((t) => t.slug === slug);
}

export function getTemaStaticParams() {
  return temas.map((tema) => ({
    slug: tema.slug,
  }));
}
